services:
  frontend:
    build:
      context: . # El contexto es el directorio actual, que contiene tu Dockerfile
      dockerfile: Dockerfile # Dockerfile que usará para construir la imagen
    ports:
      - "8081:8081" # Puerto configurado en el archivo .env
    volumes:
      - .:/frontend # Monta el código fuente local en el contenedor
      - /frontend/node_modules # Monta node_modules como un volumen separado
    command: npx expo start # Comando para iniciar el frontend
