name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            lenin.chavez/mayllu-frontend:latest  # Cambia 'username' por tu nombre de usuario en Docker Hub
            lenin.chavez/mayllu-frontend:${{ github.sha }}


