name: deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  
      - name: Build and push to Docker
        uses: docker/build-push-action@v3  
        with:
          username: ""  
          password: ""  
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ github.sha }}
